# Generated by Django 3.1.7 on 2021-03-21 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='courses',
            new_name='course',
        ),
    ]
