# Generated by Django 3.1.7 on 2021-04-03 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20210331_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='stats.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='studentID',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EvalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evalTitle', models.CharField(max_length=10)),
                ('maxPts', models.IntegerField()),
                ('totalWeight', models.IntegerField()),
                ('numAssignments', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.course')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxScore', models.IntegerField()),
                ('studentScore', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('assignmentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.evaltype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.student')),
            ],
        ),
    ]
