# Generated by Django 3.1.7 on 2021-04-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20210403_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='maxScore',
        ),
    ]
