# Generated by Django 3.1.7 on 2021-04-03 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_remove_assignment_maxscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='stats.course'),
            preserve_default=False,
        ),
    ]
