# Generated by Django 3.1.7 on 2021-04-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_assignment_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaltype',
            old_name='totalWeight',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='evaltype',
            name='numAssignments',
        ),
        migrations.AddField(
            model_name='evaltype',
            name='title',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
    ]
