# Generated by Django 3.1.7 on 2021-04-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_auto_20210404_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
    ]
