# Generated by Django 3.1.7 on 2021-04-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_assignment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaltype',
            old_name='evalTitle',
            new_name='evalType',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='title',
        ),
    ]
