# Generated by Django 3.1.7 on 2021-04-07 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_remove_evaltype_evaltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detailed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CourseAvg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avgScore', models.IntegerField()),
                ('assignmentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.evaltype')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.course')),
            ],
        ),
    ]
