# Generated by Django 3.1.7 on 2021-04-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0016_auto_20210407_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
