# Generated by Django 3.1.7 on 2021-04-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_remove_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
