# Generated by Django 3.1.7 on 2021-04-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0021_auto_20210408_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experimental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('data', models.JSONField()),
            ],
        ),
    ]
