# Generated by Django 3.1.7 on 2021-04-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0022_experimental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseavg',
            name='avgScore',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.SmallIntegerField(default=0),
        ),
    ]
