# Generated by Django 3.1.7 on 2021-04-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0025_auto_20210409_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='data',
            field=models.JSONField(default=''),
        ),
    ]
