# Generated by Django 3.1.7 on 2021-04-09 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0027_auto_20210409_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experimental',
            new_name='AssignmentAvg',
        ),
    ]
