# Generated by Django 3.1.7 on 2021-04-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0030_auto_20210409_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaltype',
            name='avg',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
