# Generated by Django 3.1.7 on 2021-04-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0031_evaltype_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaltype',
            name='grade_dist',
            field=models.JSONField(default=dict),
        ),
    ]
