# Generated by Django 3.1.7 on 2021-04-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0032_evaltype_grade_dist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaltype',
            name='grade_dist',
        ),
        migrations.AddField(
            model_name='course',
            name='grade_dist',
            field=models.JSONField(default=dict),
        ),
    ]
