# Generated by Django 3.1.7 on 2021-04-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0033_auto_20210417_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaltype',
            name='classifier',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
