# Generated by Django 3.1.7 on 2021-04-18 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0034_evaltype_classifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaltype',
            name='classifier',
        ),
        migrations.RemoveField(
            model_name='evaltype',
            name='weight',
        ),
        migrations.CreateModel(
            name='EvalWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('weight', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.course')),
            ],
        ),
        migrations.AddField(
            model_name='evaltype',
            name='eval_group',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='stats.evalweight'),
            preserve_default=False,
        ),
    ]
