# Generated by Django 3.1.7 on 2021-04-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0035_auto_20210417_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalweight',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
