# Generated by Django 3.1.7 on 2021-04-18 02:35

from django.db import migrations, models
import stats.models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0037_auto_20210417_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade_dist',
            field=models.JSONField(default=stats.models.init_grade_dist),
        ),
    ]
