# Generated by Django 3.1.7 on 2021-04-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0039_auto_20210417_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaltype',
            name='avg',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='evaltype',
            name='maxPts',
            field=models.SmallIntegerField(),
        ),
    ]
