# Generated by Django 3.1.7 on 2021-05-11 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0042_auto_20210510_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('max_pts', models.SmallIntegerField()),
                ('avg_score', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='evalweight',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='data',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentID',
        ),
        migrations.AddField(
            model_name='course',
            name='course_weights',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='student',
            name='grades_raw',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='grade_dist',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='EvalType',
        ),
        migrations.DeleteModel(
            name='EvalWeight',
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.course'),
        ),
    ]
