# Generated by Django 3.1.7 on 2021-05-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0043_auto_20210511_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='course',
            name='gradelines',
            field=models.JSONField(default={'A': 93, 'A-': 90, 'B': 83, 'B+': 87, 'B-': 80, 'C': 73, 'C+': 77, 'C-': 70, 'D': 63, 'D+': 67, 'D-': 60, 'F': 0}),
        ),
    ]
