# Generated by Django 3.1.7 on 2021-05-14 17:39

from django.db import migrations, models
import stats.models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0044_auto_20210514_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='gradelines',
            field=models.JSONField(default=stats.models.init_gradelines),
        ),
    ]
