# Generated by Django 3.1.7 on 2021-05-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0045_auto_20210514_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='letter_grade',
            field=models.CharField(default='A', max_length=2),
            preserve_default=False,
        ),
    ]
