# Generated by Django 3.1.7 on 2021-05-15 23:08

from django.db import migrations, models
import stats.models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0047_auto_20210514_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='letter_grade_dist',
            field=models.JSONField(default=stats.models.init_grade_dist),
        ),
        migrations.AlterField(
            model_name='student',
            name='letter_grade',
            field=models.CharField(default='F', max_length=2),
        ),
    ]
