# Generated by Django 3.1.7 on 2021-05-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0048_auto_20210515_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='average_grade',
            field=models.FloatField(default=0.0),
        ),
    ]
