# Generated by Django 3.1.7 on 2021-05-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0049_course_average_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show_predictive_tools',
            field=models.BooleanField(default=False),
        ),
    ]
