# Generated by Django 3.1.7 on 2021-06-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0052_course_is_curved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='show_predictive_tools',
        ),
    ]
