# Generated by Django 3.1.7 on 2021-07-01 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0054_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
