# Generated by Django 3.1.7 on 2021-07-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0055_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='sis_login_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='sis_user_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
