# Generated by Django 3.1.7 on 2021-07-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0056_auto_20210702_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
