# Generated by Django 3.1.7 on 2021-07-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0057_auto_20210702_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
